# Data Profiling - Railway Dataset

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

print("Libraries Imported Successfully")

Libraries Imported Successfully

## 2. Load Data

In [2]:
df = pd.read_csv(r'D:\Dashboards\Railway_Project\data\raw\railway.csv')

print("Data Loaded Successfully")
df.head()

Data Loaded Successfully

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,NaN,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,NaN,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,NaN,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,NaN,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,NaN,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,NaN,No

## 3. Data Overview (Shape & Info)

In [3]:
print(f"Data Shape: {df.shape}\n")
df.info()

Data Shape: (31653, 18)

<class 'pandas.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  str
 1   Date of Purchase     31653 non-null  str
 2   Time of Purchase     31653 non-null  str
 3   Purchase Type        31653 non-null  str
 4   Payment Method       31653 non-null  str
 5   Railcard             10735 non-null  str
 6   Ticket Class         31653 non-null  str
 7   Ticket Type          31653 non-null  str
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  str
 10  Arrival Destination  31653 non-null  str
 11  Date of Journey      31653 non-null  str
 12  Departure Time       31653 non-null  str
 13  Arrival Time         31653 non-null  str
 14  Actual Arrival Time  29773 non-null  str
 15  Journey Status       31653 non-null  str
 16  Reason for Delay     4172 non-null   str
 17  Refund Request       31653 non-null  str
dtypes: int64(1), str(17)
memory usage: 4.3 MB

## 4. Check for Missing Values

In [4]:
df.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard               20918
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay       27481
Refund Request             0
dtype: int64

## 5. Check for Duplicates

In [5]:
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

Number of duplicate rows: 0

## 6. Summary Statistics

In [6]:
df.describe()

              Price
count  31653.000000
mean      23.439200
std       29.997628
min        1.000000
25%        5.000000
50%       11.000000
75%       35.000000
max      267.000000

In [8]:
df.describe(include=['O'])

C:\Users\El-Wattaneya\AppData\Local\Temp\ipykernel_2812\69473401.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=['O'])

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
count,31653,31653,31653,31653,31653,10735,31653,31653,31653,31653,31653,31653,31653,29773,31653,4172,31653
unique,31653,128,24351,2,3,3,2,3,12,32,121,96,203,623,3,8,2
top,da8a6ba8-b3dc-4677-b176,2024-02-02,08:16:53,Online,Credit Card,Adult,Standard,Advance,Manchester Piccadilly,Birmingham New Street,2024-03-09,18:45:00,19:05:00,19:05:00,On Time,Weather,No
freq,1,513,6,18521,19136,4846,28595,17561,5650,7742,313,2598,1069,1013,27481,995,30535